---
name: "hello to develop branch"
on: 
   push:
      branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "hello to develop branch"
        run: echo "hello to develop branch"
