---
name: "hello to main branch"
on: 
   pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "hello to main branch"
        run: echo "hello to main branch"
